export const TOPICS = {
  NEW_MESSAGE: 'NEW_MESSAGE',
  USER_JOIN: 'USER_JOIN',
  UPDATE_NAME: 'UPDATE_NAME',
  MOUSE_MOVE: 'MOUSE_MOVE',
  MOUSE_CLICK: 'MOUSE_CLICK',
  USER_TYPE: 'USER_TYPE',
} as const;
