name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build your app
        run: |
          cd client && pnpm install && pnpm build

      - name: Commit built artifacts
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          git add .
          git commit -m "Add built artifacts"

          # Push to the builds branch
          git push origin HEAD:deploy
