name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build your app
        run: |
          cd client && pnpm install && pnpm build

      - uses: EndBug/add-and-commit@v9
        with:
          new_branch: deploy
          push: origin deploy --set-upstream --force
