name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: '${{ secrets.DEPLOY_TOKEN }}'
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build your app
        run: |
          cd client && pnpm install && pnpm build

      - uses: EndBug/add-and-commit@v9
        with:
          new_branch: deploy
          # author_name: oscarheimdahl
          # author_email: o.heimdahl@gmail.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
